### ISSUE TITLE
Typing missing from package.json for TypeScript version 

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.js.labs#41]
I need the getEntityGraph function but I'm migrating my project to TypeScript. 

I found the d.ts files after installing the package breeze-client-labs, however the typings are missing from the package.json file and when I try to import it, I get an error (module not found). Can you fix the typings ?

**Comment by graphicsxp** [comment]
I found the d.ts files after installing the package breeze-client-labs, however the typings are missing from the package.json file and when I try to import it, I get an error (module not found). Can you fix the typings ?

**Comment by graphicsxp** [comment]
I've tried to do what is described in this issue :  https://github.com/Breeze/breeze.js.labs/issues/29

```
import * as breeze from 'breeze-client';
import 'breeze-client-labs/breeze.getEntityGraph';
```

Now when I call  breeze.EntityManager.getEntityGraph ,  getEntityGraph is not recognized as a valid property of EntityManager.

**Comment by graphicsxp** [comment]
Quoting ticket #29 :

> . There were two or three that I couldn't provide type information for, because they augment the top level scope, which is not supported by TypeScript. We'll have to rewrite those extensions first, but that's for another day maybe.


I guess this hasn't been done yet ?

**Comment by marcelgood** [comment]
`import 'breeze-client-labs/breeze.getEntityGraph';`

This is all you have to do to augment the EntityManager with getEntityGraph. How are you building and bundling the application? If the module is not available at runtime, then it's most likely being optimized away during the build. If you are using the Angular CLI try adding `--build-optimizer=false` on the command line.

**Comment by graphicsxp** [comment]
Actually the import is fine. But the following line is giving an error at compile time (and it is even underlined by the IDE) : 
`breeze.EntityManager.getEntityGraph`

Indeed I can run it in dev mode. But if I run  `ng build -prod` , I get the error : 

`ERROR in angularApp/app/entity-manager.service.ts(161,41): error TS2339: Property 'getEntityGraph' does not exist on type 'typeof EntityManager'.`

**Comment by marcelgood** [comment]
Yes, of course that gives an error. `getEntityGraph` is not a class method, it's an instance method. You need to call it on an instance of the `EntityManager`.

```
import { EntityManager } from 'breeze-client';
import 'breeze-client-labs/breeze.getEntityGraph';

let em = new EntityManager();
em.getEntityGraph(roots, expand);
```

**Comment by graphicsxp** [comment]
ah yes of course, you are right ! Thank you. (I had copy/pasted my old javascript code, which wouldn't work there).
